# The name of the current backend
name: "xilef601"
# The icon of the backend. Supported values are [png, jpg, svg, null]
icon: png
# All courses of the current backend
courses:
  - Test
support_url: https://discord.linwood.tk
body: |
  Hallo! Du bist auf dem Backend von xilef601. Viel Spaß!
