# The name of the current part. The name will stand on the sidebar
name: Addition

# Optional: The description of the part
description: Hier erlernt ihr die Hauptbegriffe der Grundrechenarten.

# Assets which will be cached if the user is offline. The assets need to be in the asset directory
assets: []

# The content of the part.
items:
- name: Addition
  # Optional: Max time in seconds (here: 10 minutes)
  #time: 600
  type: quiz
  questions:
  - title: "Was ist die Addition?"
    description: "Was ist die Addition?"
    evaluation: "Man zählt Zahlen zusammen."
    answers:
    - name: "Man zählt Zahlen zusammen."
      points: 5
      correct: true
    - name: "Man zieht Zahlen voneinander ab."
    - name: "Man nimmt Zahlen so oft wie eine andere Zahl."
    - name: "Man teilt Zahlen durch eine andere."
  - title: "Wie ist die Addition aufgebaut?"
    description: "Wie ist die Addition aufgebaut?"
    evaluation: "Summand+Summand=Wert der Summe"
    answers:
    - name: "Minuend-Subtrahend=Wert der Differenz"
    - name: "Faktor*Faktor=Wert des Produkts"
    - name: "Summand+Summand=Wert der Summe"
      points: 5
      correct: true
    - name: "Dividend/Divisor=Wert des Quotienten"