# The name of the current part. The name will stand on the sidebar
name: Fachbegriffe Grundrechenarten

# Optional: The description of the part
description: Das ist der Test zu den Fachbefriffen der Grundrechenarten.

# Assets which will be cached if the user is offline. The assets need to be in the asset directory
assets: []

# The content of the part.
items:
- name: Addition
  # Optional: Max time in seconds (here: 10 minutes)
  #time: 600
  type: quiz
  questions:
  - title: "Was ist die Addition?"
    description: "Was ist die Addition?"
    evaluation: "Man zählt Zahlen zusammen."
    answers:
    - name: "Man zählt Zahlen zusammen."
      points: 5
      correct: true
    - name: "Man zieht Zahlen voneinander ab."
    - name: "Man nimmt Zahlen so oft wie eine andere Zahl."
    - name: "Man teilt Zahlen durch eine andere."
  - title: "Wie ist die Addition aufgebaut?"
    description: "Wie ist die Addition aufgebaut?"
    evaluation: "Summand+Summand=Wert der Summe"
    answers:
    - name: "Minuend-Subtrahend=Wert der Differenz"
    - name: "Faktor*Faktor=Wert des Produkts"
    - name: "Summand+Summand=Wert der Summe"
      points: 5
      correct: true
    - name: "Dividend/Divisor=Wert des Quotienten"
- name: Subtraktion
  # Optional: Max time in seconds (here: 10 minutes)
  #time: 600
  type: quiz
  questions:
  - title: "Was ist die Subtraktion?"
    description: "Was ist die Subtraktion?"
    evaluation: "Man zieht Zahlen voneinander ab."
    answers:
    - name: "Man zählt Zahlen zusammen."
    - name: "Man zieht Zahlen voneinander ab."
      points: 5
      correct: true
    - name: "Man nimmt Zahlen so oft wie eine andere Zahl."
    - name: "Man teilt Zahlen durch eine andere."
  - title: "Wie ist die Subtraktion aufgebaut?"
    description: "Wie ist die Subtraktion aufgebaut?"
    evaluation: "Minuend-Subtrahend=Wert der Differenz"
    answers:
    - name: "Minuend-Subtrahend=Wert der Differenz"
      points: 5
      correct: true
    - name: "Faktor*Faktor=Wert des Produkts"
    - name: "Summand+Summand=Wert der Summe"
    - name: "Dividend/Divisor=Wert des Quotienten"
- name: Multiplikation
  # Optional: Max time in seconds (here: 10 minutes)
  #time: 600
  type: quiz
  questions:
  - title: "Was ist die Multiplikation?"
    description: "Was ist die Multiplikation?"
    evaluation: "Man zieht Zahlen voneinander ab."
    answers:
    - name: "Man zählt Zahlen zusammen."
    - name: "Man zieht Zahlen voneinander ab."
    - name: "Man nimmt Zahlen so oft wie eine andere Zahl."
      points: 5
      correct: true
    - name: "Man teilt Zahlen durch eine andere."
  - title: "Wie ist die Multiplikation aufgebaut?"
    description: "Wie ist die Multiplikation aufgebaut?"
    evaluation: "Faktor*Faktor=Wert des Produkts"
    answers:
    - name: "Minuend-Subtrahend=Wert der Differenz"
    - name: "Faktor*Faktor=Wert des Produkts"
      points: 5
      correct: true
    - name: "Summand+Summand=Wert der Summe"
    - name: "Dividend/Divisor=Wert des Quotienten"
- name: Division
  # Optional: Max time in seconds (here: 10 minutes)
  #time: 600
  type: quiz
  questions:
  - title: "Was ist die Division?"
    description: "Was ist die Division?"
    evaluation: "Man teilt Zahlen durch eine andere."
    answers:
    - name: "Man zählt Zahlen zusammen."
    - name: "Man zieht Zahlen voneinander ab."
    - name: "Man nimmt Zahlen so oft wie eine andere Zahl."
    - name: "Man teilt Zahlen durch eine andere."
      points: 5
      correct: true
  - title: "Wie ist die Division aufgebaut?"
    description: "Wie ist die Division aufgebaut?"
    evaluation: "Faktor*Faktor=Wert des Produkts"
    answers:
    - name: "Minuend-Subtrahend=Wert der Differenz"
    - name: "Faktor*Faktor=Wert des Produkts"
    - name: "Summand+Summand=Wert der Summe"
    - name: "Dividend/Divisor=Wert des Quotienten"
      points: 5
      correct: true
- name: "Ende"
  description: "Du hast es geschafft!"
  type: text
  text: >
    "Das war es leider auch von diesem Kurs. Mehr Inhalt ist geplant und kommt bald. Bis dahin!"