# The name of the current part. The name will stand on the sidebar
name: Level 1

# Optional: The description of the part
description: Das ist ein Test-Level.

# Assets which will be cached if the user is offline. The assets need to be in the asset directory
assets: []

# The content of the part.
items:
- name: "Willkommen!"
  description: "Schön, dass du hier bist."
  type: video
  source: youtube
  url: wz36IaoYJhk
- name: Information!
  type: text
  text: >
    "Das ist der Abschnitt mit den wichtigsten Dingen zur Addition, wei zum Beispiel was die Addition überhaupt ist."
- name: Quiz
  # Optional: Max time in seconds (here: 10 minutes)
  #time: 600
  type: quiz
  questions:
  - title: "Was ist die Multiplikation?"
    description: "Was ist die Multiplikation?"
    evaluation: "Man zieht Zahlen voneinander ab."
    answers:
    - name: "Man zählt Zahlen zusammen."
    - name: "Man zieht Zahlen voneinander ab."
    - name: "Man nimmt Zahlen so oft wie eine andere Zahl."
      points: 5
      correct: true
    - name: "Man teilt Zahlen durch eine andere."
  - title: "Wie ist die Multiplikation aufgebaut?"
    description: "Wie ist die Multiplikation aufgebaut?"
    evaluation: "Faktor*Faktor=Wert des Produkts"
    answers:
    - name: "Minuend-Subtrahend=Wert der Differenz"
    - name: "Faktor*Faktor=Wert des Produkts"
      points: 5
      correct: true
    - name: "Summand+Summand=Wert der Summe"
    - name: "Dividend/Divisor=Wert des Quotienten"